# Packs the web page files (esp8266_player/web/*) into the ESP firmware, gzip-compressed, as
# esp8266_player/src/web/WebAssets.h. Run after editing anything in web/, before compiling.
# The ESP serves them with "Content-Encoding: gzip"; every current browser unpacks that itself.
# Every .html/.js/.css file in web/ is packed and served at "/<file name>" (index.html at "/"),
# so a new file needs no change here or in the firmware: just reference it from index.html.
$web = Resolve-Path "$PSScriptRoot\..\esp8266_player\web"
$out = Join-Path (Resolve-Path "$PSScriptRoot\..\esp8266_player\src\web") "WebAssets.h"
$types = @{ ".html" = "text/html"; ".js" = "application/javascript"; ".css" = "text/css" }

function Gzip([byte[]]$data) {
  $ms = New-Object IO.MemoryStream
  $gz = New-Object IO.Compression.GZipStream($ms, [IO.Compression.CompressionLevel]::Optimal)
  $gz.Write($data, 0, $data.Length); $gz.Close()
  return $ms.ToArray()
}

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine("// Generated by tools/build_web.ps1 from esp8266_player/web/. Do not edit: edit web/ and rebuild.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <Arduino.h>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("struct WebAsset { const char *path; const char *type; const uint8_t *data; size_t size; };")
$entries = @()
foreach ($f in Get-ChildItem $web -File | Sort-Object Name) {
  $ext = $f.Extension.ToLower()
  if (-not $types.ContainsKey($ext)) { continue }
  # Line endings as in git (LF): a Windows checkout may have CRLF, and the packed page must come
  # out the same everywhere, or WebAssets.h shows up as changed after every build.
  $text = [IO.File]::ReadAllText($f.FullName, [Text.Encoding]::UTF8) -replace "`r`n", "`n"
  $raw = (New-Object Text.UTF8Encoding($false)).GetBytes($text)
  $gz = Gzip $raw
  $id = "asset_" + ($f.Name -replace '[^A-Za-z0-9]', '_')
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("// $($f.Name): $($raw.Length) bytes, $($gz.Length) gzipped")
  [void]$sb.AppendLine("static const uint8_t $id[] PROGMEM = {")
  for ($i = 0; $i -lt $gz.Length; $i += 24) {
    $end = [Math]::Min($i + 24, $gz.Length) - 1
    [void]$sb.AppendLine("  " + (($gz[$i..$end] | ForEach-Object { "0x{0:X2}" -f $_ }) -join ",") + ",")
  }
  [void]$sb.AppendLine("};")
  $path = if ($f.Name -eq "index.html") { "/" } else { "/" + $f.Name }
  $entries += "  {`"$path`", `"$($types[$ext])`", $id, sizeof($id)},"
  Write-Host ("{0,-16} {1,7} bytes -> {2,6} gzipped" -f $f.Name, $raw.Length, $gz.Length)
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const WebAsset WEB_ASSETS[] = {")
$entries | ForEach-Object { [void]$sb.AppendLine($_) }
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const size_t WEB_ASSET_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);")
[IO.File]::WriteAllText($out, $sb.ToString())
Write-Host "wrote $out"
