<#
.SYNOPSIS
  Builds the demo songs into the ESP8266 firmware: packs every songs\demos\*.stepper into
  esp8266_player\src\music\EmbeddedSongs.cpp (PROGMEM arrays).

.DESCRIPTION
  Make the .stepper files first with tools\convert_demos.ps1. The song name on the player is the
  file name without ".stepper" (1-23 characters: letters, digits, space, - _ ( ) .).
  The player copies the demos into its song library on the first start and again on
  "Restore demo songs". Then compile and flash the ESP8266 as described in README.md.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File tools\build_demos.ps1
#>
$ErrorActionPreference = "Stop"
. "$PSScriptRoot\DotEnv.ps1"

$demoDir = Join-Path $ProjectRoot "songs\demos"
$outFile = Join-Path $ProjectRoot "esp8266_player\src\music\EmbeddedSongs.cpp"
$bytesPerLine = 24

$songs = @(Get-ChildItem $demoDir -Filter *.stepper | Sort-Object Name)
if (-not $songs) { throw "No .stepper files in $demoDir - run tools\convert_demos.ps1 first." }

$code = New-Object Text.StringBuilder
[void]$code.AppendLine("// Demo songs built into the firmware (PROGMEM). GENERATED by tools/build_demos.ps1 from")
[void]$code.AppendLine("// songs/demos/*.stepper - don't edit by hand. SongLibrary copies them into LittleFS on the")
[void]$code.AppendLine("// first start and again on `"Restore demo songs`"; playback always reads the LittleFS copies.")
[void]$code.AppendLine('#include "EmbeddedSongs.h"')

$tableRows = @()
foreach ($song in $songs) {
  $name = $song.BaseName
  if ($name -notmatch '^[A-Za-z0-9 _().-]{1,23}$') { throw "Song name '$name' is not allowed on the player." }
  $bytes = [IO.File]::ReadAllBytes($song.FullName)
  if ($bytes.Length -lt 12 -or [Text.Encoding]::ASCII.GetString($bytes, 0, 4) -ne "STPM") { throw "$($song.Name) is not a .stepper file." }
  $arrayName = "song_" + ($name -replace '[^A-Za-z0-9]', '_')
  [void]$code.AppendLine("")
  [void]$code.AppendLine("// $name ($($bytes.Length) bytes)")
  [void]$code.AppendLine("static const uint8_t $arrayName[] PROGMEM = {")
  for ($offset = 0; $offset -lt $bytes.Length; $offset += $bytesPerLine) {
    $last = [Math]::Min($offset + $bytesPerLine, $bytes.Length) - 1
    [void]$code.AppendLine("  " + (($bytes[$offset..$last] | ForEach-Object { "0x{0:X2}" -f $_ }) -join ",") + ",")
  }
  [void]$code.AppendLine("};")
  $tableRows += "  {`"$name`", $arrayName, sizeof($arrayName)},"
  Write-Host ("{0,-24} {1,7} bytes" -f $name, $bytes.Length)
}

[void]$code.AppendLine("")
[void]$code.AppendLine("const EmbeddedSong EMBEDDED_SONGS[] = {")
$tableRows | ForEach-Object { [void]$code.AppendLine($_) }
[void]$code.AppendLine("};")
[void]$code.AppendLine("const size_t EMBEDDED_SONG_COUNT = sizeof(EMBEDDED_SONGS) / sizeof(EMBEDDED_SONGS[0]);")
[IO.File]::WriteAllText($outFile, $code.ToString())
Write-Host "wrote $outFile ($($songs.Count) songs)"
