<#
.SYNOPSIS
  Prepares the ESP8266 firmware for compiling. Run it after a fresh clone, after editing .env
  and after editing anything in esp8266_player\web\.

.DESCRIPTION
  1. Reads .env (copy .env.example to .env first) and writes esp8266_player\src\LocalConfig.h
     with the hotspot password and the player's network name. LocalConfig.h is not committed.
  2. Packs the web page (tools\build_web.ps1) into esp8266_player\src\web\WebAssets.h.
  Then compile and flash as described in README.md.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File tools\prepare_firmware.ps1
#>
$ErrorActionPreference = "Stop"
. "$PSScriptRoot\DotEnv.ps1"

$envFile = Join-Path $ProjectRoot ".env"
if (-not (Test-Path $envFile)) {
  throw "No .env file. Copy .env.example to .env, set your own values, and run this again."
}
$settings = Read-DotEnv $envFile

$password = $settings.WIFI_AP_PASSWORD
if (-not $password -or $password.Length -lt 8 -or $password.Length -gt 63) {
  throw "WIFI_AP_PASSWORD in .env must be 8-63 characters (WPA2 rule)."
}
if ($password -match '["\\]') { throw 'WIFI_AP_PASSWORD may not contain " or \' }
$playerName = if ($settings.PLAYER_NAME) { $settings.PLAYER_NAME } else { "musicplayer" }
if ($playerName -notmatch '^[A-Za-z0-9-]{1,32}$') {
  throw "PLAYER_NAME in .env may only contain letters, digits and '-' (max 32)."
}

$localConfig = Join-Path $ProjectRoot "esp8266_player\src\LocalConfig.h"
$lines = @(
  "// Generated by tools\prepare_firmware.ps1 from .env. Do not edit and do not commit:",
  "// change .env and run the script again.",
  "#pragma once",
  "#define WIFI_AP_PASSWORD `"$password`"",
  "#define MDNS_NAME `"$playerName`""
)
[IO.File]::WriteAllText($localConfig, ($lines -join "`n") + "`n")
Write-Host "wrote $localConfig (player name: $playerName.local)"

& "$PSScriptRoot\build_web.ps1"
